
export const LISTA_JOGADORES_BEGIN= "LISTA_JOGADORES_BEGIN";
export const LISTA_JOGADORES_SUCESS="LISTA_JOGADORES_SUCESS";
export const LISTA_JOGADORES_FAILURE = "LISTA_JOGADORES_FAILURE";

export const INICIAR_BUSCA = 'INICIAR_BUSCA';
export const SUCESSO_BUSCA = 'SUCESSO_BUSCA';
export const FALHA_BUSCA = 'FALHA_BUSCA';
export const SUCESSO_BUSCAR_JOGADOR = 'BUSCAR_JOGADOR';
export const FALHA_BUSCAR_JOGADOR = 'FALHA_BUSCAR_JOGADOR';
